---
title: "Source files for the paper: *'seqwrap: an R package for flexible iterative fitting of high-dimensional data'*"
format: gfm
author: Chidimma Echebiri^1,2^  Rafi Ahmad^1,3^ Stian Ellefsen^2^ Daniel Hammarström^2,£^
---

^1^Department of Biotechnology, University of Inland Norway - Hamar, Norway

^2^Department of Public Health and Sport Sciences, University of Inland Norway - Lillehammer, Norway

^3^Institute of Clinical Medicine, Faculty of Health Sciences, UiT - The Arctic University of Norway, Hansine Hansens veg 18, 9019, Tromsø, Norway

^£^Contact: Daniel Hammarström - daniel.hammarstrom@inn.no


## Introduction

This repository contains all relevant code to reproduce the results presented in the paper *"seqwrap: an R package for flexible iterative fitting of high-dimensional data"* (in review). The paper presents the [seqwrap](https://github.com/trainome/seqwrap) package, designed for the analysis of omic-type (e.g., RNA-seq, proteomics) data using user-defined regression models.

The paper presents results from simulations defined in `simulations.R` and `simulations2.R` (see below). Since running the simulations is time-consuming, results can be downloaded from Dataverse (https://doi.org/10.18710/I7U71O) to this folder to enable direct reproducibility of the results (see instructions below, "*Downloading simulated data and estimates*").


### Repository structure and content

The script `R/make-docs.R` executes scripts in the required order to reproduce results presented in the manuscript and supplementary file. The script starts by restoring the package environment used to produce the submitted manuscript using [renv](https://rstudio.github.io/renv/index.html). Activating the package environment used to produce the manuscript is done using `renv::restore()` (see `R/make-docs.R`) 

#### Source files for docs and images

-   `supplement.qmd` Running this file reproduces the supplementary document (supplement.pdf), including the tables and figures therein. 

- `supplement.R` is a sourceable version of the quarto file (`supplement.qmd`).

- `manuscript-docx-v3.qmd` Contains the manuscript, with relevant code for presenting results.

- `img/overview.svg` contains the raw `.svg` file used to create Figure 1.

#### Scripts

- `/R` This directory contains the scripts used to produce the results presented in the paper.

     0. `check-packages.R` This script checks that all packages needed for running the analyses in the repository are installed.  

     1. `data-prep.R` The script prepares data and fits a preliminary model to the [Pillion study](https://pubmed.ncbi.nlm.nih.gov/36070371/) data set (available as part of the seqwrap package). If estimates are available, the script loads the data and prepares a model for the mean-dispersion relationship based on the data used to generate simulated counts. The output is stored in `/data/m1_results.RDS`

     2. `simulation-functions.R` Contains R functions used at different points of the analysis, such as the function to simulate data sets and summary functions. The other files (except data-prep.R) load and execute this file to make the functions and variables in the script available in the R environment

    3. `m1-m5-pillion-data.R` This file builds and saves the models based on real-world data from the [Pillion study](https://pubmed.ncbi.nlm.nih.gov/36070371/). 

    4. `make-sims.R` Runs the files `simulations.R` and `simulations2.R`, which contain the generation and modelling of the simulated data set reported in the paper. These scripts are time-consuming. Files generated by these scripts are placed in the `data_sim` folder. The generated datasets are also available for direct download from DataverseNO: https://doi.org/10.18710/I7U71O. See further instructions below.

- `/figures` The R files in this directory reproduce the figures in the paper with `figure-opts.R` defining the custom color palette used in the figures. Figure R files 2-4 require results from `data-prep.R`, `m1-m5-pillon-data.R`, and `make-sims.R`.

#### Misc

- `/resources/` contains helper files for generating the manuscript (`bibliography.bib` and .csl file).
- `/archive/` contains older version of source files and scripts.  


## Reproducing the results and figures in the article

To reproduce the analysis from scratch, we recommend you run the scripts in this order.

1. `data-prep.R`
2. `/R/m1-m5-pillion-data.R` To reproduce the case study analysis
3. `/R/make-sims.R` (or download data, see below) To reproduce the simulation data and analysis
5. `/figures/figure-2.R` Will reproduce Figure 2
6. `/figures/figure-3.R` Will reproduce Figure 3
7. `/figures/figure-4.R` Will reproduce Figure 4
8. `supplement.qmd` Reproduces the supplemental information file. 
9. `manuscript-docx-v3.qmd` Reproduces the manuscript file.


## Downloading simulated data and estimates

The analyses presented in the paper use data generated by simulations and the analyses of those data. The results can be reproduced using `make-sims.R`, however, the runtime for this process is several days on a personal computer. The datasets are available for download from DataverseNO: https://doi.org/10.18710/I7U71O. 

The downloadable data is identical to that produced by the `make-sims.R` script. Downloading the data enables direct reproduction of figures and the manuscript.

Download the files and place them in a folder called `data_sim` in the main directory. A total of 260 files (+ a README file) should be downloaded. Once downloaded, the structure of the `data_sim` folder should be:

```
-- data_sim/
   |-- estimates/
   |   |-- m1_estimates_1.RDS
   |   |-- …
   |   |-- m5_estimates_10.RDS
   |-- estimates2/
   |   |-- m1_estimates_1.RDS
   |   |-- …
   |   |-- m5_estimates_10.RDS
   |-- evaluations/
   |   |-- m1_evaluations_1.RDS
   |   |-- …
   |   |-- m5_evaluations_10.RDS
   |-- evaluations2/
   |   |-- m1_evaluations_1.RDS
   |   |-- …
   |   |-- m5_evaluations_10.RDS
   |-- simdata/
   |   |-- clean/
   |   |   |-- clean_dataset_1.RDS
   |   |   |-- …
   |   |   |-- clean_dataset_10.RDS
   |   |-- popeffect/
   |   |   |-- population_effects_1.RDS
   |   |   |-- …
   |   |   |-- population_effects_10.RDS
   |   |-- raw/ 
   |       |-- dataset_1.RDS
   |       |-- …
   |       |-- dataset_10.RDS
   |-- simdata2/
       |-- clean/
       |   |-- clean_dataset_1.RDS
       |   |-- …
       |   |-- clean_dataset_10.RDS
       |-- popeffect/
       |   |-- population_effects_1.RDS
       |   |-- …
       |   |-- population_effects_10.RDS
       |-- raw/ 
           |-- dataset_1.RDS
           |-- …
           |-- dataset_10.RDS

```
 





